#!/bin/bash
test -d "/Volumes/SSD/Develop/web"  && webdir="$_"
test -d "/Volumes/graid/web"  && webdir="$_"
if [ -z "$webdir" ]; then
	webdir=$(pwd)
fi
export "webdir"
if [ "$1" == "-l" ]; then
	local=1
	shift
else
	source $webdir/docker/docker.sh
	echo Mac
fi
if [ -z "$1" ]; then
	file=hello
else
	file="$1"
fi
dir=$(dirname $0)
cd "$dir"
rm -f libTools.so
rm -f libTools.dylib
gcc -c  jsmn.c -o jsmn.o
gcc -c  color.c -o color.o
gcc -dynamiclib -DUSE_TCL_STUBS hello.c jsmn.o color.o -L/System/Library/Frameworks/Tcl.framework -ltclstub8.5 -o libTools.dylib
err=$?
rm -f jsmn.o color.o 
if [ "$err" != "0" ]; then
	exit 1
fi
./${file}.tcl 
cp libTools.dylib ../json
if [ -n "$local" ]; then
	exit
fi
echo Raspi
TCLINC=./tcl-header
./dockcross bash -c "\$CC  -c jsmn.c -o jsmn.o"
./dockcross bash -c "\$CC  -fPIC -c color.c -o color.o"
./dockcross bash -c "\$CC -fPIC -std=gnu99 -shared -o libTools.so -DUSE_TCL_STUBS -I$TCLINC $file.c jsmn.o color.o"
ssh ccu "rm -f /usr/local/scripts/libhello.so"
ssh ccu "rm -f /usr/local/scripts/libTools.so"
cp libTools.so ../json
scp libTools.so ccu:/usr/local/scripts/libTools.so 1>/dev/null
scp ${file}.tcl ccu:/usr/local/scripts 1>/dev/null
#ssh ccu "chmod 755 /usr/local/scripts/lib${1}.so"
rm -f jsmn.o color.o 
ssh ccu "/usr/local/scripts/$file.tcl"
exit 0



ping -c1 -W1 192.168.2.83 &>/dev/null
if [ $? == 0 ]; then
	echo ubuntu
	scp "$file.c" ub:"Documents/c/$file.c" 1>/dev/null
	scp "$file.tcl" ub:"Documents/c/$file.tcl" 1>/dev/null
	ssh ub "Documents/c/compile_tcl" "$file"
fi